Add button type attribute as PL variable
forumone/gesso-theme-wordpress pull request #229
Opened 2021-02-01 17:32 UTC by karenkitchens

2021-02-01 17:42 UTC, karenkitchens commented
Closes #228

2021-02-04 16:41 UTC, coreylafferty requested changes

2021-02-04 16:41 UTC, coreylafferty commented on source/_patterns/04-components/button/button.twig
> +  <button class="{{ classes }}"{% if is_disabled %} disabled{% endif %}{% if button_type %} type="{{button_type }}"{% endif %}>{{ text }}</button>
Please add a space before the button_type variable where it's printed out.  Otherwise looks good!

2021-02-04 21:02 UTC, coreylafferty commented on source/_patterns/04-components/button/button.twig
> +  <button class="{{ classes }}"{% if is_disabled %} disabled{% endif %}{% if button_type %} type="{{button_type }}"{% endif %}>{{ text }}</button>
nm, i see an unrelated issue in these files so i'll address the variable name spacing when i fix the other issues.

2021-02-05 16:35 UTC, coreylafferty approved these changes

2021-02-05 16:36 UTC, merged