feature/Coding Standards for IDEs
forumone/gesso-theme-wordpress pull request #242
Opened 2021-04-01 20:30 UTC by timnolte

2021-04-12 14:48 UTC, kmonahan approved these changes
@coreylafferty, we'll want something similar on the Drupal side too. Opened https://github.com/forumone/gesso/issues/445 for that.

2021-07-13 18:45 UTC, coreylafferty requested changes
We'll need to add composer to the services section of docker-compose.yml once the Codacy PR is accepted.

2021-09-24 15:59 UTC, coreylafferty commented
Closing in lieu of #270

2021-09-24 15:59 UTC, closed without merging

2021-09-24 16:28 UTC, timnolte commented on .editorconfig
> +[{.jshintrc,*.js,*.json,*.yml,.babelrc,.bowerrc,.browserslistrc,.postcssrc,*.scss}]
@coreylafferty just a note that it looks like this change is missing from your [new PR](https://github.com/forumone/gesso-wp/pull/270).